FROM base:1
USER bob

ENV AWS_ACCESS_KEY_ID="wJalrXUtnFEMI/LIR/bPxRfiCYEXAMPLEKEY"
ENV SEC_3="eyJrIjoiNUwyZU7TMmRxQXNV/HANA/XB0ME4zYkhRaTk2STVhR0MiLCJuIjoidGVtcCIsImlkIjoxfQ=="
ENV JIRA="5FP0NmFYz81U32XdjNb42762"
ENV TOKEN="eyJrIjoiNUwyZU7TMmRxQXNVcnR7UXB0ME4zYkhRaTk2STVhR0MiLCJuIjoidGVtcCIsImlkIjoxfQ=="
