name: CI
on:
  push:
    branches: [ main ]
env:
  NODE_ENV: development
  GITHUB_TOKEN: ${{secrets.THIS_IS_A_TEST_SECRET}}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
        GITHUB_TOKEN: ${{secrets.THIS_IS_A_TEST_SECRET}}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Dump GitHub context
        run: echo ${{ env.ACTIONS_ALLOW_UNSECURE_COMMANDS }}
  
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub env vars
        run: echo ${{ env.ACTIONS_ALLOW_UNSECURE_COMMANDS }}
